### PR TITLE
Fixed: Validator doesn't throw UnexpectedTypeException in retry

### LINKED ISSUE #361: Validator doesn't throw UnexpectedTypeException in retry
### Expected Behavior

This is based on what was reported in #312 (it is also mentioned in the Steps to Reproduce in the linked issue - difference in behaviour is described between step 5 and 7). Validator behaviour should be consistent in a subsequent calls.

### Actual Behaviour

Given the misconfigured validation annotation (extra `@Constraint(validatedBy = {})` when there is no factory: https://github.com/micronaut-projects/micronaut-validation/issues/312#issuecomment-1968779603):
```
@Constraint(validatedBy = {})
public @interface ValidInternalId {
}
```

Validator throws only for the first call:

```java
try {
	// first try - throws
	assertThat(validator.validate(bean)).isEmpty();
} catch (Exception e) {
	// retry - works
	assertThat(validator.validate(bean)).isEmpty();
}
```

Expectation is that same exception should be thrown in the second call in a retry block.

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

https://github.com/mancze/micronaut-sandbox/tree/repro/constraint-validation-not-foundhttps://github.com/mancze/micronaut-sandbox/tree/repro/constraint-validation-not-found

### Version

4.3.8

### PR DESCRIPTION
**Pull request by altro3**
Fixed #361

### CODE REVIEW

File: validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java [hunk 1]
```diff
@@ -645,14 +645,14 @@ private <T, E> Set<? extends ConstraintViolation<?>> validatePublisherValue(Argu
...
     ) {
-        DefaultConstraintValidatorContext<T> context = new DefaultConstraintValidatorContext<>(this, null, publisher, BeanValidationContext.fromGroups(groups));
-        try (ValidationPath.ContextualPath ignored = context.getCurrentPath().addReturnValueNode()) {
-            try (ValidationPath.ContextualPath ignored1 = context.getCurrentPath().addContainerElementNode("<publisher element>",
-                ValidationPath.DefaultContainerContext.ofIterableContainer(publisherArgument.getType()))) {
-                for (DefaultConstraintValidatorContext.ValidationGroup groupSequence : context.findGroupSequences()) {
-                    try (DefaultConstraintValidatorContext.GroupsValidation ignore = context.withGroupSequence(groupSequence)) {
-                        visitElement(context, publisher, valueArgument, value, canCascade);
-                    }
+        var context = new DefaultConstraintValidatorContext<>(this, null, publisher, BeanValidationContext.fromGroups(groups));
```
Comment (dstepanov) [inline validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java]: Would you mind not making extra changes while fixing something? And doing refactoring, etc., in another PR? Otherwise, it's hard to review what changed

**Comment by dstepanov** [comment]
Please target 4.9

File: validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java (hunk 1 above)
Comment (altro3) [reply validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java]: sure, reverted

**Comment by altro3** [comment]
> Please target 4.9

done

**Comment by dstepanov** [comment]
Thanks for the fix!
